[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.28.0"
ci = "github"
installers = ["shell", "powershell", "homebrew"]
tap = "intjiraya/homebrew-tap"
formula = "constellation"

targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl",
    "x86_64-pc-windows-msvc",
    "aarch64-pc-windows-msvc",
]

pr-run-mode = "plan"

unix-archive = ".tar.xz"
windows-archive = ".zip"

install-path = "CARGO_HOME"

create-release = true
publish-jobs = ["homebrew"]
github-custom-runners = { "x86_64-unknown-linux-gnu" = "ubuntu-22.04", "aarch64-unknown-linux-gnu" = "ubuntu-22.04-arm" }

allow-dirty = ["ci"]
