[workspace]
allow_dirty = false
changelog_update = true
git_release_enable = false
publish = false
semver_check = true
dependencies_update = false
release_always = false

[changelog]
commit_parsers = [
    { message = "^feat",       group = "Added" },
    { message = "^fix",        group = "Fixed" },
    { message = "^perf",       group = "Performance" },
    { message = "^refactor",   group = "Changed" },
    { message = "^docs",       group = "Documentation" },
    { message = "^chore\\(deps\\)", group = "Dependencies" },
    { message = "^style",      skip = true },
    { message = "^chore",      skip = true },
    { message = "^ci",         skip = true },
    { message = "^test",       skip = true },
    { message = "^build",      group = "Build" },
    { body = ".*security",     group = "Security" },
    { message = "^revert",     group = "Reverted" },
]
protect_breaking_commits = true
sort_commits = "oldest"

[[package]]
name = "constellation"
changelog_path = "./CHANGELOG.md"
